version: '2'
services:
  web:
    build: ./apache/
    # extra_hosts:
    #   - "project.dev:IP-LOCAL"
    # Environment variables
    dns: 8.8.8.8
    ports:
      - "8081:80"
      #- "443:443"
    links:
      - mysql
      - mail
    volumes:
      - ./data/www:/var/www
    working_dir: /var/www
    environment:
      - VIRTUAL_HOST = kukuxumuxu.local
      - VIRTUAL_PORT = 80
      - DEGUB = FALSE
      - TIMEZONE="Europe/Madrid"
      - MEMORY_LIMIT=128M
      - UPLOAD_MAX_FILESIZE=2M
      - POST_MAX_SIZE=8M
  mysql:
    build: ./mysql
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dev8
        MYSQL_USER: dev8
        MYSQL_PASSWORD: dev8
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
  mail:
    # https://hub.docker.com/r/mailhog/mailhog/
    image: mailhog/mailhog
    ports:
     - "1025:1025"
     - "8025:8025"
